RSHA/Areas/Customer/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using RSHA.Data;
using RSHA.Models;
using RSHA.Models.ViewModels;
using RSHA.Utilities;

namespace RSHA.Areas.Customer.Controllers
{
    //[Authorize(Roles = StaticDetails.CustomerEndUser)]
    [Area("Customer")]
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _db;
        //private int PageSize = 2;
        private IConfiguration _configuration { get; }

        [BindProperty]
        public RequestsViewModel RequestsVM { get; set; }

        public RequestsController(ApplicationDbContext db, IConfiguration configuration)
        {
            _db = db;
            RequestsVM = new RequestsViewModel()
            {
                ProblemTypes = _db.ProblemTypes.ToList(),
                Requests = new Models.Requests()
            };
            _configuration = configuration;
        }

        // INDEX Action Method      --------------------------------    INDEX
        //public async Task<IActionResult> Index(int productPage = 1)
        public async Task<IActionResult> Index(int productPage = 1)
        {
            //StringBuilder param = new StringBuilder();
            //param.Append("/Customer/Requests?productsPage=:");

            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var requests = _db.Requests.Where(u => u.CustomerId == id).Include(m => m.ProblemTypes);
            //IQueryable<Models.Requests> 
            //var requests = _db.Requests.Where(u => u.CustomerId == id).ToList();

            //var count = requests.Count();

            //requests = requests.OrderBy(r => r.RequestCreated)
            //    .Skip((productPage - 1) * PageSize)
            //    .Take(PageSize).ToList();

            //PagingInfo pagingInfo = new PagingInfo
            //{
            //    CurrentPage = productPage,
            //    RequestsPerPage = PageSize,
            //    TotalRequests = count,
            //    urlParam = param.ToString()
            //};

            return View(await requests.ToListAsync());
            //return View(requests);
        }

        // GET Create Action Method --------------------------------    CREATE
        public IActionResult Create(int id)
        {
            var mech = _db.Mechanics.Find(id);
            string mechName = mech.Name;
             
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _db.ApplicationUser.Find(userId);
            
            List<string> userProfileInfo = new List<string>();
            userProfileInfo.AddRange(new List<string>
            {
                new string(user.CarModel),
                new string(user.CarLicensePlate),
                new string(user.PhoneNumber),
                new string(user.FirstName),
                new string(user.LastName)
            });

            ViewBag.userProfileInfo = userProfileInfo;
            ViewBag.mechName = mechName;
            ViewBag.id = id;

            return View(RequestsVM);
        }

        // POST Create Action Method
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST(int? id)
        {
            if (!ModelState.IsValid)
            {
                //return View(RequestsVM);
                return RedirectToAction("Create", id);
            }
            
            RequestsVM.Requests.RequestScheduledDate = RequestsVM.Requests.RequestScheduledDate
                .AddHours(RequestsVM.Requests.RequestScheduledTime.Hour)
                .AddMinutes(RequestsVM.Requests.RequestScheduledTime.Minute);

            RequestsVM.Requests.RequestCreated = DateTime.Now;

            if (RequestsVM.Requests.RequestScheduledDate.AddMinutes(1) < RequestsVM.Requests.RequestCreated)
            {
                return RedirectToAction("Create", id);
            }

            var customerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            RequestsVM.Requests.CustomerId = customerId;

            _db.Requests.Add(RequestsVM.Requests);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET Edit Action Method   --------------------------------    EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RequestsVM.Requests = await _db.Requests.Include(m => m.ProblemTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (RequestsVM.Requests == null)
            {
                return NotFound();
            }

            var mech = _db.Mechanics.Find(RequestsVM.Requests.MechanicAssigned);
            string mechName = mech.Name;

            ViewBag.mechName = mechName;

            return View(RequestsVM);
        }

        // POST Edit Action Method   --------------------------------    EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                var requestFromDb = _db.Requests.Where(m => m.Id == RequestsVM.Requests.Id).FirstOrDefault();

                RequestsVM.Requests.RequestScheduledDate = RequestsVM.Requests.RequestScheduledDate
                        .AddHours(RequestsVM.Requests.RequestScheduledTime.Hour)
                        .AddMinutes(RequestsVM.Requests.RequestScheduledTime.Minute);

                if (RequestsVM.Requests.RequestScheduledDate.AddMinutes(1) < DateTime.Now)
                {
                    return RedirectToAction("Edit", id);
                }

                requestFromDb.FirstName = RequestsVM.Requests.FirstName;
                requestFromDb.LastName = RequestsVM.Requests.LastName;
                requestFromDb.PhoneNumber = RequestsVM.Requests.PhoneNumber;
                requestFromDb.Location = RequestsVM.Requests.Location;
                requestFromDb.CarLicensePlate = RequestsVM.Requests.CarLicensePlate;
                requestFromDb.CarModel = RequestsVM.Requests.CarModel;
                requestFromDb.ProblemId = RequestsVM.Requests.ProblemId;
                requestFromDb.Message = RequestsVM.Requests.Message;
                requestFromDb.RequestScheduledDate = RequestsVM.Requests.RequestScheduledDate;

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(RequestsVM);
        }

        // GET Details Action Method    --------------------------------    DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RequestsVM.Requests = await _db.Requests.Include(m => m.ProblemTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (RequestsVM.Requests == null)
            {
                return NotFound();
            }

            var mech = _db.Mechanics.Find(RequestsVM.Requests.MechanicAssigned);
            string mechName = mech.Name;

            ViewBag.mechName = mechName;

            return View(RequestsVM);
        }

        // GET Delete Action Method --------------------------------        DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            RequestsVM.Requests = await _db.Requests.Include(m => m.ProblemTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (RequestsVM.Requests == null)
            {
                return NotFound();
            }

            var mech = _db.Mechanics.Find(RequestsVM.Requests.MechanicAssigned);
            string mechName = mech.Name;

            ViewBag.mechName = mechName;

            return View(RequestsVM);
        }

        // POST Delete Action Method --------------------------------        DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Requests request = await _db.Requests.FindAsync(id);

            if (request == null)
            {
                return NotFound();
            }
            else
            {
                _db.Requests.Remove(request);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }

        // GET Locate Action Method --------------------------------        LOCATE
        public async Task<IActionResult> Locate(string searchName = null, string searchCity = null, int? searchPostalCode = null, string searchState = null)
        {
            var mechanicList = await _db.Mechanics.ToListAsync();

            if (searchName != null) { mechanicList = mechanicList.Where(m => m.Name.ToLower().Contains(searchName.ToLower())).ToList(); }
            if (searchCity != null) { mechanicList = mechanicList.Where(m => m.City.ToLower().Contains(searchCity.ToLower())).ToList(); }
            if (searchPostalCode != null) { mechanicList = mechanicList.Where(m => m.PostalCode == searchPostalCode).ToList(); }
            if (searchState != null) { mechanicList = mechanicList.Where(m => m.State.ToLower().Contains(searchState.ToLower())).ToList(); }

            return View(mechanicList);
        }

        public async Task<IActionResult> Gmap()
        {
            ViewBag.apikey = _configuration["RSHAGmap:Apikey"];

            var mechanics = await _db.Mechanics.ToListAsync();

            //string[] mechanicHouses = new string[] { "{ lat: 59, lng: 10 }", "{ lat: 59, lng: 11 }" };

RSHA/Areas/Mechanic/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RSHA.Data;
using RSHA.Models;
using RSHA.Models.ViewModels;
using RSHA.Utilities;

namespace RSHA.Areas.Mechanic.Controllers
{
    [Authorize(Roles = StaticDetails.MechanicEndUser)]
    [Area("Mechanic")]
    public class FeedbackController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public FeedbacksViewModel FeedbacksVM { get; set; }

        public FeedbackController(ApplicationDbContext db)
        {
            _db = db;
            FeedbacksVM = new FeedbacksViewModel()
            {
                Feedbacks = _db.Feedbacks.ToList(),
                Feedback = new Models.Feedbacks()
            };
        }

        // INDEX Action Method      --------------------------------    INDEX
        public async Task<IActionResult> Index()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var feedbacks = _db.Feedbacks.Where(f => f.UserId == id);
            FeedbacksVM.Feedbacks = await Task.FromResult(feedbacks.ToList());

            //List<Feedbacks> test = await Task.FromResult(feedbacks.ToList());
            //FeedbacksVM.Feedbacks = test;

            //return View(await feedbacks.ToListAsync());
            return View(FeedbacksVM);
        }

        // POST Create Action Method
        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            FeedbacksVM.Feedback.FeedbackCreated = DateTime.Now;

            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            FeedbacksVM.Feedback.UserId = id;
            FeedbacksVM.Feedback.SenderName = User.Identity.Name;

            _db.Feedbacks.Add(FeedbacksVM.Feedback);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // GET Bug Action Method
        public IActionResult BugReport()
        {
            var bugReport = new BugRapports();

            return View(bugReport);
        }


        // POST Bug Action Method
        [HttpPost, ActionName("BugReport")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BugReportPOST(BugRapports bugReport)
        {
            if (!ModelState.IsValid)
            {
                return View(bugReport);
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _db.ApplicationUser.Find(userId);
            bugReport.UserID = user.Id;

            _db.BugRapports.Add(bugReport);
            await _db.SaveChangesAsync();

            //return RedirectToAction("Index", "Home");
            return RedirectToAction("Index", "Home", new { area = "Customer" });
        }
    }
}

RSHA/Views/Shared/_FooterPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="container-fluid p-0">
    <div class="row text-left">
        <div class="col-md-5 col-md-5">
            <h4 class="text-light">About Us</h4>
            <p class="text-muted">
                This web-application procject was made for APP2000V class at USN Norway.
            </p>
            <p class="text-muted">
                Copyright © 2019 by
                <span>Gruppe 10</span>
            </p>
        </div>
        <div class="col-md-5 col-md-5">
            <h4 class="text-light">Newsletter</h4>
            <p class="text-muted">Stay updated</p>
            <form action="" class="form-inline">
                <div class="col pl-0">
                    <div class="input-group pr-5">
                        <input type="text" class="form-control bg-dark" placeholder="Email">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fas fa-arrow-right"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2 col-sm-12">
            <h4 class="text-light">Follow Us</h4>
            <p class="text-muted">No social media currently</p>
            <div class="column">
                <i class="fab fa-facebook-f fa-3x"></i>
                <i class="fab fa-twitter fa-3x"></i>
            </div>
        </div>
    </div>
</div>

RSHA/Views/Shared/_Layout.cshtml
@using RSHA.Utilities;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RSHA</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
        <link rel="stylesheet" href="~/lib/jquery-timepicker/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css" integrity="sha384-Mmxa0mLqhmOeaE8vgOSbKacftZcsNYDjQzuCOm6D02luYSzBG8vpaOykv9lFQ51Y" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/jquery-timepicker/jquery.timepicker.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css"
              asp-fallback-href="~/lib/fontawesome/css/all.css"
              integrity="sha384-Mmxa0mLqhmOeaE8vgOSbKacftZcsNYDjQzuCOm6D02luYSzBG8vpaOykv9lFQ51Y"
              crossorigin="anonymous" />
    </environment>
</head>
<body>
    <header>
        <div class="container-fluid p">
            <div class="nav-wrapper">
                <nav id="navbar" class="navbar navbar-expand-lg">
                    <a class="navbar-brand" asp-controller="../" asp-action="Index">
                        RSHA
                        <img class="icon" src="~/images/automobile-with-wrench.svg" alt="Icon Logo">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <img class="hamburger" src="~/images/menu-circular-button.svg" alt="hamburger menu">
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <div class="mr-auto"></div>
                        <ul class="navbar-nav">
                            @if (!User.IsInRole(StaticDetails.MechanicEndUser) && User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item"><a class="nav-link" asp-area="Customer" asp-controller="Requests" asp-action="Index">Requests overview</a></li>
                                <li class="nav-item dropdown">
                                    <div class="dropdown">
                                        <a class="nav-link" asp-area="Customer" asp-controller="Requests" asp-action="Locate">Find Mechanic</a>
                                        <div class="dropdown-content">
                                            <a class="nav-link" asp-area="Customer" asp-controller="Requests" asp-action="Locate">By List</a>
                                            <a class="nav-link" asp-area="Customer" asp-controller="Requests" asp-action="Gmap">By Map</a>
                                        </div>
                                    </div>
                                </li>
                            }

                            @if (User.IsInRole(StaticDetails.MechanicEndUser))
                            {
                                <li class="nav-item"><a class="nav-link" asp-area="Mechanic" asp-controller="ReceivedRequests" asp-action="Index">Incoming requests</a></li>
                                <li class="nav-item"><a class="nav-link" asp-area="Mechanic" asp-controller="Feedback" asp-action="Index">Feedback</a></li>
                                <li class="nav-item"><a class="nav-link" asp-area="Mechanic" asp-controller="Feedback" asp-action="BugReport">Bug Reports</a></li>
                            }
                        </ul>
                        <div class="login-sm">
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                    <div class="login">
                        <partial name="_LoginPartial" />
                    </div>
                </nav>
            </div>
        </div>
        <div class="pushdown"></div>

        @*<partial name="_CookieConsentPartial" />*@

        <div class="container body-content">

            @RenderBody()
            <hr />
            <footer>
                <partial name="_FooterPartial" />
            </footer>
        </div>
    </header>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-timepicker/jquery.timepicker.js" asp-append-version="true"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" type="text/javascript"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous">

        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-timepicker/jquery.timepicker.js" asp-append-version="true"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" asp-append-version="true" type="text/javascript"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

RSHA/Views/Shared/_SendRequestToButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:250px;">
    <div class="btn-group" role="group">
        <button class="btn btn-sub btn-sub-primary text-white" style="font-size:1em;"  asp-action="Create" asp-route-id="@Model">
            <i class="fas fa-wrench"></i>&nbsp;&nbsp;Request mechanic
        </button>
        @*<a type="button" class="btn btn-primary" href="@Url.Action("Create/"+Model)">
            <i class="fas fa-wrench"></i>&nbsp;&nbsp;Request mechanic
        </a>*@
    </div>
</td>

RSHA/Views/Shared/_TableButtonAcceptRequestPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px;">
    <div class="btn-group" role="group">
        <a class="btn btn-success" asp-controller="ReceivedRequests" asp-action="Accept" asp-route-id="@Model">
            <i class="fas fa-check"></i>
        </a>
        @*<button class="btn btn-secondary" asp-area="Customer" asp-controller="Requests" asp-action="Details" asp-route-id="@Model">
                <i class="far fa-list-alt"></i>
            </button>*@
        <a class="btn btn-info" asp-area="Customer" asp-controller="Requests" asp-action="Details" asp-route-id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <form asp-action="Delete/@Model" asp-controller="ReceivedRequests" method="post">
            <input type="hidden" value="@Model" asp-route-id="@Model" />
            <button type="submit" class="btn btn-danger" style="border-radius: 0px 5px 5px 0px;"><i class="fas fa-trash-alt"></i></button>
        </form>
    </div>
</td>

@*<a class="btn btn-danger" asp-controller="ReceivedRequests" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash-alt"></i>
    </a>*@

RSHA/Views/Shared/_TableButtonAcceptRequestPartialActive.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px;">
    <div class="btn-group" role="group">
        @*<a class="btn btn-success" asp-controller="ReceivedRequests" asp-action="Finish" asp-route-id="@Model">
            <i class="fas fa-check-double"></i>
        </a>*@
        <form asp-action="Finish/@Model" asp-controller="ReceivedRequests" method="post">
            <input type="hidden" value="@Model" asp-route-id="@Model" />
            <button type="submit" onclick="accept()" class="btn btn-success accept" style="border-radius: 5px 0px 0px 5px;"><i class="fas fa-check-double"></i></button>
        </form>
        <a class="btn btn-info" asp-area="Customer" asp-controller="Requests" asp-action="Details" asp-route-id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <form asp-action="Delete/@Model" asp-controller="ReceivedRequests" method="post">
            <input type="hidden" value="@Model" asp-route-id="@Model" />
            <button type="submit" onclick="del()" class="btn btn-danger" style="border-radius: 0px 5px 5px 0px;"><i class="fas fa-trash-alt"></i></button>
        </form>
    </div>
</td>

RSHA/Views/Shared/_TableButtonAcceptRequestPartialHistory.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px;">
    <div class="btn-group" role="group">
        <button type="button" disabled class="btn btn-dark" href="#">
            <i class="fas fa-check"></i>
        </button>
        <a class="btn btn-info" asp-area="Customer" asp-controller="Requests" asp-action="Details" asp-route-id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <button type="button" disabled class="btn btn-dark" href="#">
            <i class="fas fa-trash-alt"></i>
        </button>
    </div>
</td>

RSHA/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px;">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model)">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model)">
            <i class="far fa-list-alt"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete/"+Model)">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

RSHA/Views/Shared/_TableButtonPartialHistory.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px;">
    <div class="btn-group" role="group">
        <button type="button" disabled class="btn btn-dark" href="#">
            <i class="fas fa-edit"></i>
        </button>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model)">
            <i class="far fa-list-alt"></i>
        </a>
        <button type="button" disabled class="btn btn-dark" href="#">
            <i class="fas fa-trash-alt"></i>
        </button>
    </div>
</td>